export const siteContent = {
  merek: 'Crimson Rift Studio',
  nav: {
    links: [
      { name: 'Beranda', path: '/' },
      { name: 'Layanan', path: '/services' },
      { name: 'Galeri', path: '/gallery' },
      { name: 'Tentang', path: '/about' },
    ],
    desktopCta: 'Mulai Arahan',
    mobileEyebrow: 'Ruang Navigasi',
    mobileCta: 'Konsultasi Tenang',
    ariaHome: 'Beranda Crimson Rift Studio',
    ariaToggle: 'Buka navigasi',
  },
  shared: {
    whatsappUrl: 'https://wa.me/6281398621530',
    clientMarquee: 'Dipercaya oleh visi yang berani',
    preloaderBrand: 'Crimson Rift',
    preloaderText: 'Membuka ruang visual',
    audioOn: 'Heningkan suasana',
    audioOff: 'Nyalakan suasana',
    audioOnAria: 'Matikan suasana',
    audioOffAria: 'Nyalakan suasana',
  },
  home: {
    hero: {
      imageAlt: 'Komposisi arsitektur gelap bernuansa crimson',
      eyebrow: 'Studio Digital Butik',
      meta: 'Crimson / Rift / Studio',
      title: 'Merek Anda tidak harus terasa biasa.',
      body: 'Saat visual buntu, digital terasa datar, dan konversi melemah, Crimson Rift Studio merancang celah baru: arah yang jernih, identitas yang kuat, dan pengalaman yang membuat orang percaya lebih cepat.',
      primaryCta: 'Mulai dari arahan',
      secondaryCta: 'Masuki galeri',
      pillars: ['Jernih', 'Berani', 'Bernilai'],
    },
    pains: [
      { title: 'Visual terasa biasa', copy: 'Merek sudah bekerja keras, tetapi tampilannya belum membuat orang berhenti, percaya, lalu memilih.' },
      { title: 'Arah digital kabur', copy: 'Situs, konten, dan identitas berjalan sendiri-sendiri tanpa ritme yang menyatukan persepsi.' },
      { title: 'Konversi kehilangan tenaga', copy: 'Audiens datang, melihat sebentar, lalu pergi karena pengalaman belum terasa meyakinkan.' },
    ],
    painSection: {
      eyebrow: 'Masalah yang sering tersembunyi',
      title: 'Bisnis bisa hebat, tetapi tetap terasa tak terlihat.',
      body: 'Banyak pemilik bisnis bukan kekurangan kualitas. Mereka kekurangan panggung visual yang mampu menerjemahkan kualitas itu menjadi rasa percaya.',
    },
    roleSection: {
      imageAlt: 'Ruang editorial yang tenang dan premium',
      quote: 'Kami tidak membuat merek lebih ramai. Kami membuatnya lebih jelas.',
      eyebrow: 'Peran Crimson Rift',
      title: 'Celah antara biasa dan bernilai harus dirancang, bukan ditunggu.',
      body: 'Crimson adalah intensitas: keberanian untuk terlihat dengan emosi, ketajaman, dan rasa. Rift adalah celah: jarak antara bisnis yang hanya hadir dan merek yang benar-benar diingat. Di sanalah kami bekerja.',
      qualities: ['Arah yang jernih', 'Identitas yang kuat', 'Pengalaman hidup'],
    },
    gallerySection: { eyebrow: 'Koleksi pendek', title: 'Cuplikan rasa visual yang kami kejar.' },
    gallery: [
      { title: 'Ruang Identitas', type: 'Arahan Merek', image: 'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?q=80&w=1500&auto=format&fit=crop' },
      { title: 'Lanskap Digital', type: 'Pengalaman Situs', image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?q=80&w=1600&auto=format&fit=crop' },
      { title: 'Gerak yang Tenang', type: 'Kampanye Visual', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1500&auto=format&fit=crop' },
    ],
    serviceSection: { eyebrow: 'Yang kami bangun', title: 'Sistem kreatif yang membuat merek terasa lebih utuh.' },
    services: [
      { title: 'Situs Sinematik', copy: 'Antarmuka cepat, jernih, dan berkarakter untuk mengubah kunjungan menjadi rasa percaya.', path: '/services/web-development' },
      { title: 'Identitas Visual', copy: 'Sistem lambang, warna, tipografi, dan bahasa visual yang membuat merek terasa matang.', path: '/services/logo-branding' },
      { title: 'Foto & Gerak', copy: 'Aset visual editorial yang membawa suasana, detail, dan emosi merek ke permukaan.', path: '/services/photography-videography' },
      { title: 'Mesin Atensi', copy: 'Strategi konten dan kampanye yang membuat merek hadir konsisten tanpa kehilangan kelas.', path: '/services/social-media' },
    ],
    final: {
      eyebrow: 'Jika waktunya sudah tepat',
      title: 'Mari membuat merek Anda terasa pantas dipilih.',
      cta: 'Buka percakapan',
    },
  },
  galleryPage: {
    eyebrow: 'Galeri Privat',
    title: 'Berjalan pelan di antara karya.',
    body: 'Sebuah koridor horizontal berisi fragmen visual, sistem, dan suasana. Geser perlahan—setiap karya dirancang untuk terasa seperti ruang pamer kecil.',
    hint: 'Geser horizontal',
    projects: [
      { title: 'Niaga Obsidian', category: 'Situs / Konversi', year: '2026', image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?q=80&w=1800&auto=format&fit=crop', note: 'Ruang jual yang terasa tenang, cepat, dan meyakinkan.' },
      { title: 'Identitas Monohaus', category: 'Identitas Visual', year: '2026', image: 'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?q=80&w=1700&auto=format&fit=crop', note: 'Sistem visual untuk merek yang ingin tampil matang tanpa berteriak.' },
      { title: 'Gerak Rift', category: 'Kampanye Sinematik', year: '2025', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1700&auto=format&fit=crop', note: 'Gerak, cahaya, dan ritme untuk mengubah pesan menjadi suasana.' },
      { title: 'Sinyal Sosial', category: 'Mesin Atensi', year: '2025', image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1800&auto=format&fit=crop', note: 'Konten yang konsisten, rapi, dan cukup tajam untuk diingat.' },
      { title: 'Produk Noir', category: 'Arahan Seni', year: '2025', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1800&auto=format&fit=crop', note: 'Detail produk diperlakukan seperti objek galeri, bukan sekadar katalog.' },
    ],
    exhibitLabel: 'Eksibisi',
    closingEyebrow: 'Karya berikutnya',
    closingTitle: 'Jika merek Anda membutuhkan ruang pamer sendiri, kami bisa membangunnya dengan tenang.',
    closingCta: 'Rancang eksibisi Anda',
  },
  about: {
    eyebrow: 'Tentang Studio',
    title: 'Crimson Rift adalah cara kami membaca jarak.',
    intro: 'Jarak antara kualitas dan persepsi. Antara niat besar dan tampilan yang belum sepadan. Antara merek yang bekerja keras dan audiens yang belum benar-benar merasakannya.',
    panelAlt: 'Crimson Rift Studio',
    statement: 'Kami percaya kemewahan digital lahir dari rasa yang jelas, bukan ornamen yang berlebihan.',
    manifesto: [
      { title: 'Crimson adalah intensitas', copy: 'Ia bukan merah yang berisik. Ia adalah hasrat yang matang, keberanian yang terkendali, dan daya visual yang membuat sesuatu terasa hidup.' },
      { title: 'Rift adalah celah', copy: 'Celah antara bisnis yang sekadar hadir dan merek yang meninggalkan kesan. Di celah itu, strategi dan estetika bertemu.' },
      { title: 'Studio adalah disiplin', copy: 'Kami merapikan intuisi menjadi sistem: halaman, identitas, konten, dan pengalaman yang dapat tumbuh tanpa kehilangan rasa.' },
    ],
    philosophy: {
      eyebrow: 'Filosofi kerja',
      title: 'Kami tidak mengejar ramai. Kami mengejar resonansi.',
      body: 'Sebuah merek tidak harus menjelaskan dirinya terlalu keras ketika setiap detail sudah bekerja: ritme halaman, bobot huruf, kedalaman warna, cara gambar muncul, hingga kalimat yang membuat orang merasa dipahami.',
      points: [
        'Membaca masalah sebelum menggambar bentuk.',
        'Menyusun sistem sebelum mempercantik permukaan.',
        'Membuat pengalaman terasa mahal tanpa kehilangan kehangatan.',
      ],
    },
    final: {
      eyebrow: 'Untuk merek yang siap naik kelas',
      title: 'Kami membantu Anda terlihat setara dengan nilai yang Anda bawa.',
      cta: 'Ceritakan arah Anda',
    },
  },
  servicesPage: {
    eyebrow: 'Ruang Layanan',
    title: 'Sistem untuk membuat merek terasa utuh.',
    body: 'Kami menggabungkan strategi, rasa visual, antarmuka, narasi, dan ritme konten agar bisnis Anda tidak hanya terlihat—tetapi terasa pantas dipercaya.',
    label: 'Layanan',
    cards: [
      { title: 'Situs Sinematik', path: '/services/web-development', image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?q=80&w=1800&auto=format&fit=crop', copy: 'Situs, halaman arahan, dan pengalaman digital yang cepat, rapi, serta terasa meyakinkan sejak detik pertama.', span: 'lg:col-span-7' },
      { title: 'Identitas Visual', path: '/services/logo-branding', image: 'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?q=80&w=1500&auto=format&fit=crop', copy: 'Lambang, warna, tipografi, dan sistem visual yang membuat merek terasa matang, langka, dan mudah dikenali.', span: 'lg:col-span-5' },
      { title: 'Foto & Videografi', path: '/services/photography-videography', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1500&auto=format&fit=crop', copy: 'Aset visual editorial untuk membangun suasana, kedalaman, dan daya tarik yang tidak terasa generik.', span: 'lg:col-span-5' },
      { title: 'Strategi Atensi', path: '/services/social-media', image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1800&auto=format&fit=crop', copy: 'Sistem konten, kampanye, dan pengelolaan sosial yang menjaga merek tetap hadir dengan ritme yang elegan.', span: 'lg:col-span-7' },
    ],
    closing: 'Tidak yakin harus mulai dari mana? Kami dapat membaca kondisi merek Anda terlebih dahulu, lalu menyusun prioritas yang paling masuk akal.',
    cta: 'Diskusikan kebutuhan',
  },
  contact: {
    eyebrow: 'Mulai Percakapan',
    title: 'Ceritakan bagian merek yang ingin Anda angkat.',
    body: 'Kami akan membaca konteksnya dengan tenang, lalu mengubahnya menjadi arah visual, ruang lingkup, dan langkah eksekusi yang lebih jernih.',
    sideTitle: 'Jalur langsung',
    sideBody: 'Jika Anda lebih nyaman memulai dari percakapan singkat, kirim pesan melalui WhatsApp. Kami akan membantu merapikan arahan setelahnya.',
    sideCta: 'Hubungi studio',
    sentTitle: 'Arahan tersimpan.',
    sentBody: 'Formulir ini siap dihubungkan ke sistem pengiriman. Secara visual, alur arahan sudah dirancang untuk terasa tenang dan premium.',
    fields: { name: 'Nama', email: 'Surel bisnis', message: 'Apa yang sedang terasa buntu, dan hasil seperti apa yang ingin Anda rasakan dari merek ini?' },
    serviceLabel: 'Kebutuhan utama',
    services: ['Situs', 'Identitas', 'Foto / Video', 'Konten Sosial'],
    budgetLabel: 'Tingkat investasi',
    budgets: [
      ['arah', 'Arah Awal'],
      ['kurasi', 'Kurasi Premium'],
      ['signature', 'Karya Khusus'],
      ['retainer', 'Kerja Berkala'],
    ],
    upload: 'Referensi atau arahan opsional',
    submit: 'Kirim arahan',
  },
  footer: {
    eyebrow: 'Crimson Rift Studio',
    title: 'Saat identitas perlu terasa tak tergantikan.',
    body: 'Kami merancang arah visual, situs, dan sistem konten untuk merek yang ingin tampil lebih tenang, lebih tajam, dan lebih bernilai.',
    cta: 'Mulai percakapan',
  },
};
